spring:
  cache:
    caffeine:
      spec: expireAfterWrite=1m

  jackson:
    default-property-inclusion: non_null
  cloud:
    openfeign:
      oauth2:
        enabled: true
        clientRegistrationId: twitch
      client:
        config:
          twitch-api:
            url: https://api.twitch.tv/helix
            loggerLevel: basic
            default-request-headers:
              Client-Id: "dro6hvmhytkwngljfva940e5tj4564"
  security:
    oauth2:
      client:
        registration:
          twitch:
            authorization-grant-type: client_credentials
            client-authentication-method: client_secret_post
            client-id: "dro6hvmhytkwngljfva940e5tj4564"
            client-secret: "l7rxrxaf8qszr35ompo5nplhvpboqq"
        provider:
          twitch:
            token-uri: https://id.twitch.tv/oauth2/token

  sql:
    init:
      mode: always
      schema-locations: "classpath:database-init.sql"



  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:3306/twitch?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: DEBUG # Incoming HTTP requests
    com.projects.twitch.external.TwitchApiClient: DEBUG # Outgoing HTTP requests
    org.springframework.jdbc.core: DEBUG # SQL



